### ISSUE TITLE
녹음 기능

### ISSUE THREAD

**Issue by Zepelown** [LIE-ON/Lieon_application#1]
## 어떤 기능인가요?

어플리케이션 녹음 기능 추가

## 작업 상세 내용

- [x] 녹음 페이지 디자인 구성
- [x] 녹음 기능 구성
- [x] 녹음 파일 wav 파일로 저장
- [x] 녹음 기록 저장 (내부 DB)

**Comment by LimDoHyeon** [comment]
gd

**Comment by Zepelown** [comment]
완료

**Comment by Zepelown** [comment]
완료
